### ISSUE TITLE
You rock! using it but have some troubles with importing it

### ISSUE THREAD

**Issue by omerman** [TanStack/svelte-query#3]
Currently I kind of copied the src folder and importing the files I need in a weird way :)

When can we expect this to be published? or am I missing something?

Thanks

**Comment by amen-souissi** [comment]
Hello :)
We are currently working on a first version of the documentation with examples on codesandbox. The release of the first version will probably be for the next few weeks (maybe with this package name @tanstack/svelte-query)
Thank you !

**Comment by omerman** [comment]
@amen-souissi Any news? :grimacing:

**Comment by omerman** [comment]
@amen-souissi I started using this(a moment ago) ->> @reactstack/svelte-query, it seems to be the same except for the name..

**Comment by amen-souissi** [comment]
Please don't use it! it's only for testing... the publication process is being automated :)

**Comment by omerman** [comment]
@amen-souissi While I wait for the official release, Im using it(Not holding anyone else accountable).. there is no other good alternative and it works perfectly.
I tested several key features such as enabling/disabling fetches, updating the cached data, prefetching seems to also work..

Anyways I'll keep waiting for the official release, thank you :)

**Comment by amen-souissi** [comment]
@reactstack/svelte-query@1.0.0-beat.2 published

**Comment by omerman** [comment]
@amen-souissi Ill have a look today

**Comment by evdama** [comment]
Hi folks... looks interresting... just came accross it about 10min ago and one question I have is this: how does it relate to e.g. rxjs? Is it build upon or does it require graphQL? Is there anything comparable people might know already so to understand what it actually is? 🤔
