### ISSUE TITLE
queryKeyHashFn not working correctly?

### ISSUE THREAD

**Issue by omerman** [TanStack/svelte-query#5]
Hey again :)

I believe queryClient.setQueryData doesnt use the queryKeyHashFn I supplied, and therefore the updater I'm passing receives undefined for the current cached value argument.

I recently added queryKeyHashFn, and now when using queryClient.setQueryData my updater always receives undefined.

Could you please take a look?

Thank you

**Comment by amen-souissi** [comment]
Hello @omerman :)

Try with the latest beta version please (@reactstack/svelte-query@1.0.0-beat.3)

Thank you

**Comment by omerman** [comment]
Works well! :)

**Comment by amen-souissi** [comment]
@reactstack/svelte-query is no longer supported. Please use @sveltestack/svelte-query instead.
